### ISSUE TITLE
The app does not send an email. Logs indicate there is an issue with the SMTP sender.

### ISSUE THREAD

**Issue by partofaplan** [partofaplan/zebs_app#2]
The app is meant to send an email when the file is uploaded. However, this appears to only work on localhost. In AWS, there is something blocking the connection out and it's timing out. 

`Oct 21 00:40:44 ip-172-31-47-171 web: Error: Connection timeout
Oct 21 00:40:44 ip-172-31-47-171 web: at SMTPConnection._formatError (/var/app/current/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)
Oct 21 00:40:44 ip-172-31-47-171 web: at SMTPConnection._onError (/var/app/current/node_modules/nodemailer/lib/smtp-connection/index.js:770:20)
Oct 21 00:40:44 ip-172-31-47-171 web: at Timeout.<anonymous> (/var/app/current/node_modules/nodemailer/lib/smtp-connection/index.js:235:22)
Oct 21 00:40:44 ip-172-31-47-171 web: at listOnTimeout (internal/timers.js:549:17)
Oct 21 00:40:44 ip-172-31-47-171 web: at processTimers (internal/timers.js:492:7) {
Oct 21 00:40:44 ip-172-31-47-171 web: code: 'ETIMEDOUT',
Oct 21 00:40:44 ip-172-31-47-171 web: command: 'CONN'
Oct 21 00:40:44 ip-172-31-47-171 web: }`

**Comment by partofaplan** [comment]
I resolved this issue by switching back to "gmail" transporter and using a dev email address I have never used before. This might only work for a little while though because gmail tends to catch up and block AWS ip addresses.
